server:
  port: 8081
app:
  grouped:
    threadsCount: 10
spring:
  datasource:
    driver-class: org.postgresql.Driver
    url: "jdbc:postgres://localhost:5432/test_wallet_balance_service_db"
    username: test_wallet_balance_service_usr
    password: test_wallet_balance_service_pass
    hikari:
      minimumIdle: 5
      maximumPoolSize: 20
      idleTimeout: 30000
      poolName: HikariCP
      maxLifetime: 180000
      connectionTimeout: 5000
  liquibase:
    enabled: true
    user: test_wallet_balance_service_usr
    password: test_wallet_balance_service_pass
    change-log: classpath:/db/changelog/db.changelog-master.xml
  jpa:
    show-log: false
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect